name: Reason
favicon: null
layout_spectrum: 0.7935859884601086
typography_spectrum: 0.5185926542617381
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.2710974046494812
  lightness: 0.8518028652761132
  saturation: 0.1792305449489504
  rhythmicContrast: 0.6054423418827355
purpose: []
